# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-16 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='question_description',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='description',
            new_name='quiz_description',
        ),
    ]
