# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-20 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180816_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='canPublish',
            field=models.BooleanField(default=False),
        ),
    ]
